name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:
  
jobs:
  CD:
    name: Continuous Delivery
    runs-on: ubuntu-latest
    steps:
      - name: SSH into production server
        uses: appleboy/ssh-action@master
        with:
          host: 207.180.207.114
          username: root
          key: ${{secrets.CONTABO_SSH_PK}}
          port: 22
          script: |
            cd jobot
            git pull origin master
            git status
            npm install
            npm run build
            pm2 restart all
